sudo: false
language: node_js
node_js:
  - 11 # use nodejs v11 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo clean # generate static files
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
